# Generated by Django 5.1 on 2024-09-17 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_productentry_delete_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productentry',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='productentry',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='productentry',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
